version = 1
SPDX-FileCopyrightText = "none"
SPDX-License-Identifier = "CC0-1.0"
SPDX-PackageName = "MimeTreeParser"
SPDX-PackageSupplier = "Carl Schwan <carl@carlschwan.eu>"

[[annotations]]
path = ["autotests/testdata/**", "autotests/gnupg_home/**", "README.md", ".gitignore", "screenshots/screenshot.png", "screenshots/widgets.png", "readme-build-ftime.txt", "REUSE.toml", "src/core/mimetreeparser-core.qdoc", "src/core/mimetreeparser-core.qdocconf", "src/core/mimetreeparser-index.qdoc", "src/widgets/mimetreeparser-widgets.qdoc", "src/widgets/mimetreeparser-widgets.qdocconf"]
precedence = "aggregate"
SPDX-FileCopyrightText = "none"
SPDX-License-Identifier = "CC0-1.0"
